// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type Message struct {
	Data  string `json:"data"`
	Error *Error `json:"error"`
}
